{{- if .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inference-gateway.fullname" . }}
  labels:
    {{- include "inference-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "inference-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
